// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.196
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ScriptError
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "bb430f0f-6e1a-498c-9c86-9c1f102d43ea";
        public const string guidAutoLoadString = "40abc622-657a-46bb-b29e-417a8a43821e";
        public const string guidValidatorPackageCmdSetString = "0ead6319-7c08-496d-b89e-3909f4082b77";
        public const string guidBrowserLinkCmdSetString = "30947ebe-9147-45f9-96cf-401bfc671a82";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidAutoLoad = new Guid(guidAutoLoadString);
        public static Guid guidValidatorPackageCmdSet = new Guid(guidValidatorPackageCmdSetString);
        public static Guid guidBrowserLinkCmdSet = new Guid(guidBrowserLinkCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EnableScriptError = 0x0100;
        public const int IDG_BROWSERLINK_COMMANDS = 0x2001;
    }
}
